
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfexkzudrbyculteagmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZXhrenVkcmJ5Y3VsdGVhZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTUyOTIsImV4cCI6MjA1OTk5MTI5Mn0.r2s7Eaa6A25bok_r1yieNRscFwli66TfcbtLnrf91xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
